/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#f6fff3",
        "surface-container": "#efeded",
        "surface-dim": "#dbdad9",
        "tertiary-fixed-dim": "#c4c7c3",
        "on-primary-fixed": "#00210c",
        tertiary: "#595d59",
        "surface-bright": "#fbf9f8",
        "on-error": "#ffffff",
        "primary-container": "#008743",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#005226",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary-fixed": "#e0e3df",
        "on-secondary-container": "#636262",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e2",
        "primary-fixed": "#8afaa6",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        primary: "#006b33",
        surface: "#fbf9f8",
        outline: "#6e7a6e",
        "surface-container-highest": "#e4e2e2",
        "on-background": "#1b1c1c",
        "outline-variant": "#bdcabc",
        "on-tertiary-container": "#fafdf8",
        "inverse-surface": "#303031",
        "tertiary-container": "#727572",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3e4a3f",
        "inverse-primary": "#6ddd8c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#444844",
        "secondary-container": "#e2dfde",
        background: "#fbf9f8",
        "surface-tint": "#006d35",
        secondary: "#5f5e5e",
        "surface-container-high": "#e9e8e7",
        "surface-container-low": "#f5f3f3",
        error: "#ba1a1a",
        "inverse-on-surface": "#f2f0f0",
        "primary-fixed-dim": "#6ddd8c",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#191c1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "gutter-md": "16px",
        "margin-lg": "32px",
        "container-padding": "24px",
      },
      fontFamily: {
        "arabic-display": ["Amiri", "serif"],
        "arabic-body": ["Amiri", "serif"],
        "headline-md": ["Noto Serif", "serif"],
        "headline-lg": ["Noto Serif", "serif"],
        "display-lg": ["Noto Serif", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
